#include <stdio.h>
#include <stdlib.h>
// #include "dynamicArray_1.h"
// #include "dynamicArray_2.h"
// #include "dynamicArray_3.h"
// #include "projectile.h"
// #include "projectile_2.h"


int main()
{   
    printf("hello world!\n");
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        